FROM docker.io/ocamlpro/ocaml:4.14.2 as base

ARG RMTLD3SYNTH_VERSION="v0.5-x" # this will be replaced by the build environment

RUN sudo apk add python3 build-base bash gmp-static

RUN opam switch create . ocaml-system --deps-only --locked

RUN opam pin add dolmen https://github.com/Gbury/dolmen.git#a0f1bc66e7256fff1068ac0df525a2d23c1f3ea7 -y
RUN opam pin add dolmen_type https://github.com/Gbury/dolmen.git#a0f1bc66e7256fff1068ac0df525a2d23c1f3ea7 -y
RUN opam pin add dolmen_loop https://github.com/Gbury/dolmen.git#a0f1bc66e7256fff1068ac0df525a2d23c1f3ea7 -y

RUN git clone --branch ${RMTLD3SYNTH_VERSION} https://github.com/anmaped/rmtld3synth.git
RUN git clone --branch z3-4.12.3 https://github.com/Z3Prover/z3.git

RUN opam install zarith ppx_sexp_conv sexplib bigarray-compat ocamlfind ppx_yojson_conv
RUN cd z3 && eval $(opam env) && python scripts/mk_make.py --ml --staticlib && cd build && make

# fix
RUN sed -i "s~api/ml/libz3ml~api/ml/libz3ml-static~g" z3/build/Makefile
RUN sed -i "s~api/ml/dllz3ml.so~api/ml/dllz3ml-static.so~g" z3/build/Makefile
RUN ls -l z3/build && sudo cp z3/build/libz3-static.a /usr/lib/libz3-static.a

RUN cd z3/build && sudo sh -c "eval $(opam env) make install"

RUN sed -i "s/-cclib -lstdc++/:standard -cclib -static -cclib -no-pie/g" rmtld3synth/src/dune
RUN cd rmtld3synth && eval $(opam env) && ./configure --prefix=/usr && opam exec -- make all


FROM docker.io/alpine:3.20

COPY --from=base /home/ocaml/_opam/bin/rmtld3synth /usr/bin

#ENTRYPOINT /bin/sh
WORKDIR /root