opam-version: "2.0"
name:         "rmtld3synth"
version:      "0.6-dev"
maintainer:   "André Pedro <apedro.1@gmail.com>"
authors:      "André Pedro <apedro.1@gmail.com>"
homepage:     "https://github.com/anmaped/rmtld3synth"
bug-reports:  "https://github.com/anmaped/rmtld3synth/issues"
dev-repo:     "git+https://github.com/anmaped/rmtld3synth.git"
doc:          "https://github.com/anmaped/rmtld3synth#documentation"
synopsis:     "Runtime Verification toolchain"
description:  "Runtime Verification toolchain for generating monitors based on the restricted Metric Temporal Logic with Durations."
license:      "LGPL-3.0-only WITH OCaml-LGPL-linking-exception"

depends: [
  "ocamlfind" {build}
  "dune" {build}
  "bigarray-compat" {build}
  "sexplib" {build}
  "ppx_sexp_conv" {build}
  "dolmen_loop" {build}
  "yojson" {build}
  "ppx_yojson_conv" {build}
  "z3" {<="4.12.3"}
]

pin-depends: [
  ["dolmen.dev" "git+https://github.com/Gbury/dolmen.git#a0f1bc66e7256fff1068ac0df525a2d23c1f3ea7"]
  ["dolmen_type.dev" "git+https://github.com/Gbury/dolmen.git#a0f1bc66e7256fff1068ac0df525a2d23c1f3ea7"]
  ["dolmen_loop.dev" "git+https://github.com/Gbury/dolmen.git#a0f1bc66e7256fff1068ac0df525a2d23c1f3ea7"]
]

build: [
  ["./configure" "--prefix=%{prefix}%"]
  [make "setup"]
  ["dune" "subst"] {pinned}
  ["dune" "build" "-p" name "-j" jobs]
]

install: [
  ["dune" "install" "-p" name]
]

run-test: [
  ["dune" "runtest" "-p" name "-j" jobs]
]

remove: [
  ["dune" "uninstall" "-p" name]
]
