(set-info :smt-lib-version 2.6)
(set-logic AUFDTNIRA)
(set-info :source |https://github.com/anmaped/rmtld3synth|)
(set-info :license "https://creativecommons.org/licenses/by/4.0/")
(set-option :produce-models true)
(define-sort Proptype () Int)
(define-sort Time () Int)
(define-sort Index () Int)
(declare-datatype Duration ((dnone) (dsome (dval Int))))
(declare-datatype Pair (par (X Y) ((mk-pair (first X) (second Y)))))
(define-sort Trace () (Array Index Proptype))
(define-sort Trace_ () (Array Index Real))
(declare-datatype Fourvalue ((FVTRUE) (FVFALSE) (FVUNKNOWN) (FVSYMBOL)))
(declare-datatype Threevalue ((TVTRUE) (TVFALSE) (TVUNKNOWN)))
(define-fun tvnot ((phi Threevalue)) Threevalue
  (ite (= phi TVTRUE) TVFALSE (ite (= phi TVFALSE) TVTRUE TVUNKNOWN)))
(define-fun tvor ((phi1 Threevalue) (phi2 Threevalue)) Threevalue
  (ite (or (= phi1 TVTRUE) (= phi2 TVTRUE)) TVTRUE
   (ite (and (= phi1 TVFALSE) (= phi2 TVFALSE)) TVFALSE TVUNKNOWN)))
(define-fun tvlessthan ((eta1 Duration) (eta2 Duration)) Threevalue
  (ite (or (= eta1 dnone) (= eta2 dnone)) TVUNKNOWN
   (ite (< (dval eta1) (dval eta2)) TVTRUE TVFALSE)))
(define-fun mapb4 ((phi Threevalue)) Fourvalue
  (ite (= phi TVTRUE) FVTRUE (ite (= phi TVFALSE) FVFALSE FVUNKNOWN)))
(define-fun mapb3 ((p (Pair Bool Fourvalue))) Threevalue
  (ite (= (second p) FVTRUE) TVTRUE
   (ite (= (second p) FVSYMBOL) (ite (first p) TVUNKNOWN TVFALSE)
    (ite (= (second p) FVFALSE) TVFALSE TVUNKNOWN))))
(define-fun evali ((b1 Threevalue) (b2 Threevalue)) Fourvalue
  (ite (= b2 TVFALSE) (ite (= b1 TVTRUE) FVSYMBOL (mapb4 b1)) (mapb4 b2)))
(declare-const trc Trace)
(declare-const trc_time Trace_)
(declare-const trc_size Time)
(declare-fun mapt (Index) Real)
(assert (forall ((i Index))
         (ite (< 0 i) (= (mapt i) (+ (mapt (- i 1)) (select trc_time i)))
          (= (mapt i) (select trc_time i)))))
(define-fun ev_prop ((mk Trace) (mt Time) (p Proptype)) Threevalue
  (ite (>= trc_size mt) (ite (= (select mk mt) p) TVTRUE TVFALSE) TVUNKNOWN))
(declare-const v_gamma!3 Index)
(assert (= v_gamma!3 10))
(define-fun evalb!3 ((mk Trace) (mt Time) (mtb Time) (v Fourvalue)) Fourvalue
  (ite (= v FVSYMBOL) (evali (ev_prop mk mt 2) (ev_prop mk mt 1)) v))
(declare-fun evalfold!3 (Time Time) Fourvalue)
(assert (forall ((x Time) (i Time))
         (ite (< i x)
          (= (evalb!3 trc x i (evalfold!3 (- x 1) i)) (evalfold!3 x i))
          (= (evalb!3 trc x i FVSYMBOL) (evalfold!3 x i)))))
(define-fun evalc!3 ((mt Time) (mtb Time)) (Pair Bool Fourvalue)
  (mk-pair (>= (+ v_gamma!3 mtb) trc_size) (evalfold!3 (- mt 1) mtb)))
(define-fun until_less_op!3 ((mt Time) (mtb Time)) Threevalue
  (mapb3 (evalc!3 mt mtb)))
(define-fun allcheck ((mk Trace) (mt Time)) Bool
  (= (until_less_op!3 (+ mt v_gamma!3) mt) TVTRUE))
(assert (forall ((t Time)) (< 0 (select trc_time t))))
(assert (allcheck trc 0))
(check-sat)
(get-model)
(get-info :all-statistics)

