(set-info :smt-lib-version 2.6)
(set-logic AUFDTNIRA)
(set-info :source |https://github.com/anmaped/rmtld3synth|)
(set-info :license "https://creativecommons.org/licenses/by/4.0/")
(set-option :produce-models true)
(define-sort Proptype () Int)
(define-sort Time () Int)
(define-sort Index () Int)
(declare-datatype Duration ((dnone) (dsome (dval Int))))
(declare-datatype Pair (par (X Y) ((mk-pair (first X) (second Y)))))
(define-sort Trace () (Array Index Proptype))
(define-sort Trace_ () (Array Index Real))
(declare-datatype Fourvalue ((FVTRUE) (FVFALSE) (FVUNKNOWN) (FVSYMBOL)))
(declare-datatype Threevalue ((TVTRUE) (TVFALSE) (TVUNKNOWN)))
(define-fun tvnot ((phi Threevalue)) Threevalue
  (ite (= phi TVTRUE) TVFALSE (ite (= phi TVFALSE) TVTRUE TVUNKNOWN)))
(define-fun tvor ((phi1 Threevalue) (phi2 Threevalue)) Threevalue
  (ite (or (= phi1 TVTRUE) (= phi2 TVTRUE)) TVTRUE
   (ite (and (= phi1 TVFALSE) (= phi2 TVFALSE)) TVFALSE TVUNKNOWN)))
(define-fun tvlessthan ((eta1 Duration) (eta2 Duration)) Threevalue
  (ite (or (= eta1 dnone) (= eta2 dnone)) TVUNKNOWN
   (ite (< (dval eta1) (dval eta2)) TVTRUE TVFALSE)))
(define-fun mapb4 ((phi Threevalue)) Fourvalue
  (ite (= phi TVTRUE) FVTRUE (ite (= phi TVFALSE) FVFALSE FVUNKNOWN)))
(define-fun mapb3 ((p (Pair Bool Fourvalue))) Threevalue
  (ite (= (second p) FVTRUE) TVTRUE
   (ite (= (second p) FVSYMBOL) (ite (first p) TVUNKNOWN TVFALSE)
    (ite (= (second p) FVFALSE) TVFALSE TVUNKNOWN))))
(define-fun evali ((b1 Threevalue) (b2 Threevalue)) Fourvalue
  (ite (= b2 TVFALSE) (ite (= b1 TVTRUE) FVSYMBOL (mapb4 b1)) (mapb4 b2)))
(declare-const trc Trace)
(declare-const trc_time Trace_)
(declare-const trc_size Time)
(declare-fun mapt (Index) Real)
(assert (forall ((i Index))
         (ite (< 0 i) (= (mapt i) (+ (mapt (- i 1)) (select trc_time i)))
          (= (mapt i) (select trc_time i)))))
(define-fun ev_prop ((mk Trace) (mt Time) (p Proptype)) Threevalue
  (ite (>= trc_size mt) (ite (= (select mk mt) p) TVTRUE TVFALSE) TVUNKNOWN))
(declare-const v_dt!3 Duration)
(define-fun indicator!3 ((mk Trace) (mt Time)) Int
  (ite (= (ev_prop mk mt 1) TVTRUE) 1 0))
(declare-fun evaleta!3 (Time Time) Duration)
(assert (forall ((x Time) (i Time))
         (=> (>= x 0)
          (ite (and (>= i 0) (< i x))
           (= (+ (dval (evaleta!3 (- x 1) i)) (indicator!3 trc x))
            (dval (evaleta!3 x i)))
           (= (dval (evaleta!3 x i)) (indicator!3 trc x))))))
(define-fun duration_op!3 ((mt Time) (mtb Time)) Duration
  (ite (and (>= trc_size mt) (< (dval (dsome 2)) (- (mapt mt) (mapt mtb))))
   (evaleta!3 (- mt 1) mtb) dnone))
(define-fun allcheck ((mk Trace) (mt Time)) Bool
  (= (tvlessthan (duration_op!3 (+ mt (dval v_dt!3)) mt) (dsome 10)) TVTRUE))
(assert (forall ((t Time)) (< 0 (select trc_time t))))
(assert (allcheck trc 0))
(check-sat)
(get-model)
(get-info :all-statistics)

